export interface FormData {
  address: string,
  detailAddress: string,
  realEstate: string,
  realEstatePriceType: string,
  depositAmount: number,
  rentAmount: number,
  maintenanceFee: number,
  maintenanceFeeItems: string[],
  floor: string,
  sunlightDirection: string,
  leasableArea: number,
  pet: boolean,
  canceled: boolean,
  thumbnail: string,
};